ALTER TABLE products
    ADD COLUMN cost DECIMAL(12, 2) NOT NULL DEFAULT 0.00;

ALTER TABLE products
    ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE products
    ADD COLUMN description VARCHAR(500) NULL;
